# Generated by Django 2.0 on 2018-07-24 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='bio',
            new_name='headline',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='favorite_color',
        ),
        migrations.AddField(
            model_name='myuser',
            name='country',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='industry',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='zipcode',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
