# Generated by Django 2.0.7 on 2018-07-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20180723_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
